name: welcome

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  thank_first_time_contributors:
    runs-on: ubuntu-latest
    # Only welcome genuine external contributors:
    # - skip bots
    # - skip maintainers (owner/member/collaborator) so self-merged maintainer
    #   PRs don't get falsely flagged as a "first contribution"
    if: >-
      (github.event.pull_request.user.type || github.event.issue.user.type) != 'Bot'
      && github.event.pull_request.author_association != 'OWNER'
      && github.event.pull_request.author_association != 'MEMBER'
      && github.event.pull_request.author_association != 'COLLABORATOR'
      && github.event.issue.author_association != 'OWNER'
      && github.event.issue.author_association != 'MEMBER'
      && github.event.issue.author_association != 'COLLABORATOR'
    steps:
      - name: Welcome first-time contributors
        uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          pr_message: |
            Welcome to Speechmatics Academy @${{ github.event.pull_request.user.login }}! Thanks for your first contribution.

            If you find this project useful:
            - Star the repo: https://github.com/speechmatics/speechmatics-academy
            - Check out the docs: https://docs.speechmatics.com

            We're excited to have you here!
          issue_message: |
            Thanks for opening your first issue @${{ github.event.issue.user.login }}!

            We appreciate you taking the time to report this. Our team will take a look as soon as possible.

            In the meantime, feel free to:
            - Star the repo: https://github.com/speechmatics/speechmatics-academy
            - Check out the docs: https://docs.speechmatics.com

            We're glad to have you here!
